library-mysql:
    container_name: library-mysql
    image: mysql:latest
    # volumes:
    #     - ~/volumes/jhipster/hello/mysql/:/var/lib/mysql/
    environment:
        - MYSQL_USER=root
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=library
    ports:
        - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl
